# Generated by Django 3.0.5 on 2023-06-17 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_remove_reclamation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 17, 16, 4, 51, 344794)),
        ),
    ]
