# Generated by Django 3.0.5 on 2023-06-17 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_reclamation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 17, 18, 27, 57, 993716), null=True),
        ),
    ]
